version: "3"
services:
  selenoid:
    image: 'aerokube/selenoid:1.1.1'
    volumes:
      - /etc/selenoid:/etc/selenoid:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui:1.0.0
    ports:
      - "8080:8080"



#docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
#   aerokube/cm:1.0.0 selenoid --last-versions 2 --tmpfs 128 --pull \
#   > /etc/selenoid/browsers.json
#
#   docker run -d --name selenoid -p 4444:4444 \
#       -v /etc/selenoid:/etc/selenoid:ro \
#       -v /var/run/docker.sock:/var/run/docker.sock \
#       aerokube/selenoid:1.1.1
#
#        docker run -d --name selenoid-ui --net host \
#           aerokube/selenoid-ui:1.0.0